### ISSUE TITLE
TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by Guibod** [bryanrsmith/eslint-plugin-no-unused-vars-rest#1]
I don't know where the source code causing this hides itself but i stumble on this stacktrace:

```
TypeError: Cannot read property 'type' of null
    at isDestructuredVarWithRestProperty (/home/guibod/dev/webapp/node_modules/eslint-plugin-no-unused-vars-rest/dist/rules/no-unused-vars.js:67:15)
    at RuleContext.report (/home/guibod/dev/webapp/node_modules/eslint-plugin-no-unused-vars-rest/dist/rules/no-unused-vars.js:45:9)
    at EventEmitter.Program:exit (/home/guibod/dev/webapp/node_modules/eslint/lib/rules/no-unused-vars.js:596:33)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.leaveNode (/home/guibod/dev/webapp/node_modules/eslint/lib/util/node-event-generator.js:49:22)
    at CodePathAnalyzer.leaveNode (/home/guibod/dev/webapp/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:628:23)
    at CommentEventGenerator.leaveNode (/home/guibod/dev/webapp/node_modules/eslint/lib/util/comment-event-generator.js:110:23)
    at Controller.leave (/home/guibod/dev/webapp/node_modules/eslint/lib/eslint.js:921:36)
    at Controller.__execute (/home/guibod/dev/webapp/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/home/guibod/dev/webapp/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at Controller.Traverser.controller.traverse (/home/guibod/dev/webapp/node_modules/eslint/lib/util/traverser.js:36:33)
    at EventEmitter.module.exports.api.verify (/home/guibod/dev/webapp/node_modules/eslint/lib/eslint.js:915:23)
    at processText (/home/guibod/dev/webapp/node_modules/eslint/lib/cli-engine.js:262:31)
    at CLIEngine.executeOnText (/home/guibod/dev/webapp/node_modules/eslint/lib/cli-engine.js:749:26)
    at verify (/home/guibod/dev/webapp/node_modules/gulp-eslint/index.js:20:25)

```

I can fix this by altering the plugin this way:

```
function isDestructuredVarWithRestProperty(node) {
    var parent = node.parent;

  if (!parent) {
    return false;
  }

    return parent.type === 'Property' && parent.parent.type === 'ObjectPattern' && parent.parent.properties.some(function (p) {
        return p.type === 'ExperimentalRestProperty';
    });
}

```

**Comment by bryanrsmith** [comment]
Thanks, @Guibod! I'll push a fix momentarily. Are you able to identify the source code being linted that's causing this error? I'm having a hard time reproducing locally and I'd like to add a test.

**Comment by Guibod** [comment]
I'd really like to help you @bryanrsmith but unfortunately i'm up to 702 errors in my project so that's really hard to find the source problem at the moment. :)

you know a way for me to reverse engineer that ?

**Comment by bryanrsmith** [comment]
Published v1.0.4 with your proposed fix. Hopefully you'll now see an error reported in the offending file instead of a crash :-)

**Comment by bryanrsmith** [comment]
@Guibod Did you get a chance to try out the new version? I was never able to reproduce this myself, and want to make sure the issue has been resolved.

**Comment by Guibod** [comment]
Well, i've tried it, it works but i've seen no output, I guess I fixed the problematic line of code.
Unfortunately I can't reproduce it, and don't really have time to git bissect my code to find it again.

Sorry, mate.

Thanks for the fix nonetheless.

**Comment by bryanrsmith** [comment]
No worries. Thanks for reporting it!
